name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    name: jdk-${{ matrix.java }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup jdk-${{ matrix.java }}
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Cache
        uses: actions/cache@master
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk${{ matrix.java }}-maven-
      - name: Setup
        run: | 
          sudo apt install -y \
          openjfx=8u161-b12-1ubuntu2 \
          libopenjfx-java=8u161-b12-1ubuntu2 \
          libopenjfx-jni=8u161-b12-1ubuntu2
      - name: Build
        run: mvn verify --batch-mode -Dmaven.javadoc.skip=true -V --no-transfer-progress
